/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package developer;

public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
    int n = sc.nextInt();
    int[] arr = new int[n];

    for(int i = 0; i < n; i++){
        arr[i] = sc.nextInt();
    }

    Arrays.sort(arr);

    System.out.println(arr);
    }
}
